// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrxUlKUjyuC6-vTeb1EI1Dxtl9oRalZiM',
    appId: '1:385153470085:web:4ab45b4b3ffa9bbd2c23ec',
    messagingSenderId: '385153470085',
    projectId: 'flutter-chat-app-8fd7d',
    authDomain: 'flutter-chat-app-8fd7d.firebaseapp.com',
    storageBucket: 'flutter-chat-app-8fd7d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlFCuuwsXY9BYVV3DH5x3cpSCOAp84DEs',
    appId: '1:385153470085:android:12f21162e6a8f84d2c23ec',
    messagingSenderId: '385153470085',
    projectId: 'flutter-chat-app-8fd7d',
    storageBucket: 'flutter-chat-app-8fd7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqx8iTV1EFdILREiWoo8QbtgH-F0SSupc',
    appId: '1:385153470085:ios:2913ca0d39149b3e2c23ec',
    messagingSenderId: '385153470085',
    projectId: 'flutter-chat-app-8fd7d',
    storageBucket: 'flutter-chat-app-8fd7d.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrxUlKUjyuC6-vTeb1EI1Dxtl9oRalZiM',
    appId: '1:385153470085:web:751eb9107ee161f92c23ec',
    messagingSenderId: '385153470085',
    projectId: 'flutter-chat-app-8fd7d',
    authDomain: 'flutter-chat-app-8fd7d.firebaseapp.com',
    storageBucket: 'flutter-chat-app-8fd7d.firebasestorage.app',
  );

}